/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:16e982f6-9de3-4081-9d81-f007b1114da0",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_899JZ4TzX",
    "aws_user_pools_web_client_id": "69tc18cgclte5kflhpbg7l38a4",
    "oauth": {}
};


export default awsmobile;
